// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task1_api;

namespace Task1_api.Migrations
{
    [DbContext(typeof(DbClass))]
    partial class DbClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Task1_api.Todo_list", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DandT");

                    b.Property<bool>("is_completed");

                    b.Property<bool>("is_deleted");

                    b.Property<string>("todo_title");

                    b.HasKey("id");

                    b.ToTable("todo");
                });

            modelBuilder.Entity("Task1_api.tasks_list", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("creation_time");

                    b.Property<DateTime?>("deletion_time");

                    b.Property<bool>("is_completed");

                    b.Property<bool>("is_deleted");

                    b.Property<string>("task_name");

                    b.Property<DateTime?>("updation_time");

                    b.HasKey("id");

                    b.ToTable("tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
